CREATE TABLE [dbo].[worksheet] (
    [IdMinor]    INT           IDENTITY (1, 1) NOT NULL,
    [Surname]    NVARCHAR (50) NULL,
    [Name]       NVARCHAR (50) NULL,
    [Patronymic] NTEXT NULL,
    [Birthday]   DATE          NULL,
	[PlaceBirth]   NVARCHAR (MAX) NULL,
    [Location]     NVARCHAR (MAX) NULL,
    [Registration] NVARCHAR (MAX) NULL, 
    [Education] NVARCHAR (MAX) NULL, 
	[WorkPlace] NVARCHAR (MAX) NULL, 
	[SurnameMother]   NVARCHAR (50) NULL,
	[NameMother]   NVARCHAR (50) NULL,
	[PatronymicMother]   NVARCHAR (50) NULL,
	[SurnameFather]   NVARCHAR (50) NULL,
	[NameFather]   NVARCHAR (50) NULL,
	[PatronymicFather]   NVARCHAR (50) NULL,
	[Status]   NVARCHAR (50) NULL,
	[Source]   NVARCHAR (MAX) NULL,
	[Article]   NVARCHAR (MAX) NULL,
	[Cause] NVARCHAR (MAX) NULL,
	[DateDeregistration] DATE NULL,
	[BasisOfPuttingOnRecord] NVARCHAR (MAX) NULL,
	[Number] INT NULL,
	[DateDecision] DATE NULL,
	[Health] NVARCHAR (MAX) NULL,
	[Dependency] NVARCHAR (MAX) NULL,
	[DateOffense] DATE NULL, 
    [Offense] NVARCHAR (MAX) NULL,
	[ParticipantsOffense] NVARCHAR (MAX) NULL, 
    [ArticleOffense] NVARCHAR(MAX) NULL, 
    [TypePunishment] NVARCHAR(MAX) NULL,
);

